from .step2_get_detail import GetDetail
from .step4_product import Step4
from .step3_detail_quchong import Step3
from .去重 import Quchong
from .step7_imgs import Step7
from .step8_wp_to_shopify import Step8WpToShopify
from .step9_dz import Step9Discount
from .step10_col import Step10Collection
from .step6_variable import Step6Variable
