[site]
base_url = "https://loopearplugs.com"
site = "loopearplugs"
site_type = "shopify"
zk = 0.3

[request]
max_retry = 3
time_out = 30
headers = ""
cookies = ""
images_split = ""
custom_key = ""

[request.browser]
enabled = true

