[site]
base_url = ""
site = ""
site_type = "mg_shopify"
zk = 0.3

[request]
max_retry = 3
time_out = 30
headers = ""
cookies = ""
images_split = ""
custom_key = ""

[request.browser]
enabled = false

