from .step_get_detail import GetDetail
from .step_get_product import Get_Product
from .step_detail_quchong import Detail_QuChong
from .去重 import Quchong
from .step_imgs import Replace_imgs
from .step_wp_to_shopify import WpToShopify
from .step_shopify_dz import Shopify_dz
from .step_col import Collection
from .step_variable import Variable
